version: '3.3'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./app
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./app/src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_act
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
        ports:
            - "9906:3306"